### ISSUE TITLE
Form Validation for Create Unit, Create Lesson, and Add Vocab Item modals

### ISSUE THREAD

**Issue by ashayp22** [hack4impact-uiuc/7000-languages#186]
**Describe the bug**
We should validate the forms on the `Create Unit`, `Create Lesson`, and `Add Vocab Item` modals. We can do this by:

1. Disabling the submit button (can gray out like on the Apply to Contribute page)
2. Adding a * next to required fields

Check out `client/src/pages/Apply` for examples on how to do the form validation.

**Comment by rustom** [comment]
Are the `validate()` function and `FormControl` components in `Apply.js` necessary (and corresponding components I'd add to `CreateUnit`, etc.)? It seems sufficient to just disable the submit button by creating the `areAllFilled` bool and passing it to the `Drawer` component in `CreateUnit.js`, like this:

```js
const areAllFilled = name !== '' && purpose !== ''

return (
    <Drawer
      titleText="Add Custom Unit"
      successText="Create Unit"
      successCallback={success}
      closeCallback={close}
      isDisabled={!areAllFilled}
      body={body}
    />
  )
```

The same can be done for lesson and vocab item.
