### ISSUE TITLE
White screen appears when pressing "done" on iOS 14.8.1

### ISSUE THREAD

**Issue by masgras2** [hack4impact-uiuc/7000-languages#201]
**Describe the bug**
When inside any text entry box and the blue "done" button on the keyboard is pressed, a large, white screen appears which is unable to be closed, blocking all app content. When this happens, the app must be reloaded to resume functionality.

**To Reproduce**
1. Go to any text entry box on iOS 14.8.1 (eg. Manage Units => Create Unit => "Give your unit a name")
2. Click on the blue "done" button
3. White screen will appear, blocking access to all content

**Expected behavior**
The text box should close.

**Screenshots**
![image](https://user-images.githubusercontent.com/111911351/192677078-68c71fc4-e5fd-41bf-a77f-fef24334e66c.png)
Above: The text box with the done button shown
![image](https://user-images.githubusercontent.com/111911351/192677029-84285449-ecab-44c0-bc4d-52abfc52cb1f.png)
Above: The white box covering most of the screen

**Environment**
 - Device: iPhone SE 2nd Edition
 - OS: iOS 14.8.1

**Additional context**
This problem is not unique to this app, and has been encountered on other apps as well.

**Comment by ashayp22** [comment]
Think this is an Expo issue. Tested on TestFlight with @masgras2's iOS 14 device.
