### ISSUE TITLE
New vocab page doesn't display images/audio

### ISSUE THREAD

**Issue by masgras2** [hack4impact-uiuc/7000-languages#265]
**Describe the bug**
In the Manage Vocab Page (#250) commit, the vocab page now displays as a numbered list, with no images or audio displayed. On the previous version of the page, there is now no option to add a vocab item.

**To Reproduce**
1. Go to any vocab page
2. Add image or audio to an item
3. No image or audio is displayed

**Expected behavior**
Images and audio will be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/111911351/199877068-f201cc74-65e1-485a-88c6-4340e400a430.png)
![image](https://user-images.githubusercontent.com/111911351/199877093-a44a006d-f62d-4075-bcd1-002b3930dc32.png)

**Environment (please complete the following information):**
 - Device: iPhone SE 2
 - OS: iOS 14.8.1

**Comment by ashayp22** [comment]
Resolved in #286
